-- Allow authenticated tenant users to write audit events generated by their own requests.
-- Apply this migration in Supabase SQL Editor after the previous migrations.

create or replace function public.audit_event_write_allowed(
  p_organization_id uuid,
  p_actor_id uuid
)
returns boolean
language sql
stable
security definer
set search_path = public, pg_catalog
as $$
  select
    p_actor_id = nullif(current_setting('app.current_user_id', true), '')::uuid
    and (
      exists (
        select 1
        from public.platform_admins pa
        where pa.user_id = p_actor_id
      )
      or exists (
        select 1
        from public.organization_memberships om
        where om.organization_id = p_organization_id
          and om.user_id = p_actor_id
          and om.is_active = true
      )
    );
$$;

grant execute on function public.audit_event_write_allowed(uuid, uuid) to authenticated;

drop policy if exists audit_events_insert on public.audit_events;

create policy audit_events_insert
on public.audit_events
for insert
to authenticated
with check (
  public.audit_event_write_allowed(organization_id, actor_id)
);
