"""Knowledge-document and permission-aware vector-search repositories."""

from __future__ import annotations

from dataclasses import dataclass
from uuid import UUID

from psycopg import Connection

from outbound_ai.db.connection import TenantContext


@dataclass(frozen=True, slots=True)
class KnowledgeDocument:
    id: UUID
    organization_id: UUID
    title: str
    storage_path: str
    status: str


@dataclass(frozen=True, slots=True)
class KnowledgeMatch:
    id: UUID
    document_id: UUID
    organization_id: UUID
    document_title: str
    storage_path: str | None
    content_raw: str
    page_number: int | None
    similarity: float
    dense_similarity: float = 0.0
    lexical_score: float = 0.0


def create_document(
    connection: Connection,
    *,
    organization_id: UUID,
    uploaded_by: UUID,
    title: str,
    storage_path: str,
    mime_type: str,
    language: str = "ar",
) -> KnowledgeDocument:
    """Register a private storage object; RLS checks org-admin ownership."""

    row = connection.execute(
        """
        insert into public.knowledge_documents
          (organization_id, uploaded_by, title, storage_path, mime_type, language)
        values (%s, %s, %s, %s, %s, %s)
        returning id, organization_id, title, storage_path, status
        """,
        (organization_id, uploaded_by, title, storage_path, mime_type, language),
    ).fetchone()
    if row is None:
        raise RuntimeError("Knowledge document was not created")
    return KnowledgeDocument(**row)


def insert_chunks(
    connection: Connection,
    *,
    organization_id: UUID,
    document_id: UUID,
    chunks: list[tuple[int, str, str, int | None, str | None]],
) -> None:
    """Insert (index, raw, normalized, page, embedding-text) chunk records.

    ``embedding_text`` is the pgvector literal generated by the embedding adapter,
    for example ``[0.01,0.02,...]``. The dimension is enforced by PostgreSQL.
    """

    with connection.cursor() as cursor:
        for chunk_index, content_raw, content_norm, page_number, embedding_text in chunks:
            cursor.execute(
                """
                insert into public.knowledge_chunks
                  (organization_id, document_id, chunk_index, content_raw,
                   content_norm, page_number, embedding)
                values (%s, %s, %s, %s, %s, %s, %s::extensions.vector)
                on conflict (document_id, chunk_index)
                do update set
                  content_raw = excluded.content_raw,
                  content_norm = excluded.content_norm,
                  page_number = excluded.page_number,
                  embedding = excluded.embedding
                """,
                (
                    organization_id,
                    document_id,
                    chunk_index,
                    content_raw,
                    content_norm,
                    page_number,
                    embedding_text,
                ),
            )


def match_chunks(
    connection: Connection,
    *,
    context: TenantContext,
    query_embedding: str,
    match_count: int = 8,
) -> list[KnowledgeMatch]:
    """Search only the active organization through the permission-aware SQL RPC."""

    if context.organization_id is None:
        raise ValueError("An organization context is required for knowledge retrieval")
    if not 1 <= match_count <= 100:
        raise ValueError("match_count must be between 1 and 100")

    rows = connection.execute(
        """
        select m.id, m.document_id, m.organization_id,
               d.title as document_title, d.storage_path,
               m.content_raw, m.page_number, m.similarity
        from public.match_knowledge_chunks(
          %s::extensions.vector(384), %s::uuid, %s::integer
        ) m
        join public.knowledge_documents d on d.id = m.document_id
        """
        , (query_embedding, context.organization_id, match_count),
    ).fetchall()
    return [KnowledgeMatch(**row) for row in rows]


def hybrid_match_chunks(
    connection: Connection,
    *,
    context: TenantContext,
    query_text: str,
    query_embedding: str,
    match_count: int = 8,
) -> list[KnowledgeMatch]:
    """Run dense plus lexical retrieval through the tenant-filtered SQL RPC."""

    if context.organization_id is None:
        raise ValueError("An organization context is required for knowledge retrieval")
    if not query_text.strip():
        raise ValueError("query_text cannot be empty")
    if not 1 <= match_count <= 100:
        raise ValueError("match_count must be between 1 and 100")
    rows = connection.execute(
        """
                select m.id, m.document_id, m.organization_id,
               d.title as document_title, d.storage_path,
               m.content_raw, m.page_number,
               m.dense_similarity, m.lexical_score, m.similarity
        from public.hybrid_knowledge_chunks(
          %s::extensions.vector(384), %s, %s::uuid, %s::integer
        ) m
        join public.knowledge_documents d on d.id = m.document_id
        """
,
        (query_embedding, query_text, context.organization_id, match_count),
    ).fetchall()
    return [KnowledgeMatch(**row) for row in rows]
